version: "3.7"

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgresPassGym
        POSTGRES_DB: postgres
